application: davidlutest

version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: (.*\.html)

- url: /(.*\.js)
  static_files: \1
  upload: (.*\.js)

- url: /.*
  script: helloworld.py
